server:
  port: ${PORT:9001}

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}

spring:
  main:
    banner-mode: "off"
  application:
    name: api


api:
  constraints:
    sliding-time-interval: 60 # in seconds
  broker:
    groupId: index
    producer:
      tickTopic: ticks
    consumer:
      statsTopic: stats
