server:
  port: ${PORT:9002}

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}

spring:
  main:
    banner-mode: "off"
  quartz:
    job-store-type: memory
    properties:
      org.quartz.jobStore.class: org.quartz.simpl.RAMJobStore
  application:
    name: statistics

statistics:
  constraints:
    sliding-time-interval: 60 # in seconds
  broker:
    bootstrap-servers: localhost:9092
    groupId: index
    consumer:
      tickTopic: ticks
    producer:
      statsTopic: stats